# Generated by Django 2.2.1 on 2019-09-15 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=100, verbose_name='Название викторины')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_questions',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='questions.Quiz'),
            preserve_default=False,
        ),
    ]
