# Generated by Django 2.2.1 on 2019-09-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20190915_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_var',
            field=models.CharField(default=0, max_length=200, verbose_name='Вариант 3'),
            preserve_default=False,
        ),
    ]
