# Generated by Django 2.2.1 on 2019-09-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20190918_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Ценность вопроса'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
