# Generated by Django 2.2.1 on 2019-09-17 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_score',
            name='user_score',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_score',
            name='user_score_in_question',
            field=models.IntegerField(verbose_name='Счет пользователя в вопросе'),
        ),
    ]
