# Generated by Django 2.2.1 on 2019-09-17 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
